name: pypsa-ariadne
channels:
- conda-forge
- bioconda
- gurobi
dependencies:
- python>=3.8
- pip

- pre-commit
- black

- jupyter
- jupyterlab

  # Dependencies of the workflow itself
- xlrd
- openpyxl!=3.1.1
- pycountry
- seaborn
- snakemake-minimal>=8.5
- memory_profiler
- yaml
- pytables
- lxml
- powerplantmatching>=0.5.11
- numpy
- pandas>=1.4
- geopandas>=0.11.0
- atlite>=0.2.9
- dask
- xarray
- rioxarray
- netcdf4
- networkx
- scipy
- shapely>=2.0
- pyomo
- gurobi
- ipopt
- matplotlib<3.6
- proj
- fiona
- country_converter
- geopy
- tqdm
- pytz
- tabula-py
- pyxlsb
- graphviz
- tsam>=1.1.0
- pypsa>=0.27.0
- highs
- pyam
- ruamel.yaml

  # Keep in conda environment when calling ipython
- ipython

  # GIS dependencies:
- cartopy
- descartes
- rasterio!=1.2.10

- pip:
  - snakemake-storage-plugin-http
  - snakemake-executor-plugin-slurm
  - snakemake-executor-plugin-cluster-generic



