# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  name: "240201-365H-revertaviationsep"
  scenarios:
    enable: true
  shared_resources: true #stops recalculating
  disable_progressbar: true


iiasa_database:
  db_name: ariadne_intern
  model_name: Hybrid
  scenario: 8Gt_EnSec
  region: Deutschland

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  simpl:
  - ''
  ll:
  - v1.2
  clusters:
  - 22
  opts:
  - ''
  sector_opts:
    - 365H-T-H-B-I-A-solar+p3-linemaxext15
  planning_horizons:
  - 2020
  - 2030
  - 2040
  - 2050

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
# Germany plus 12 "Stromnachbarn"
countries: ['AT', 'BE', 'CH', 'CZ', 'DE', 'DK', 'FR', 'GB', 'LU', 'NL', 'NO', 'PL', 'SE']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: false # set to false once initial data is retrieved
  retrieve_cutout: false # set to false once initial data is retrieved
clustering:
  focus_weights:
  # 22 nodes: 8 for Germany, 2 each for Denmark and UK, 1 per each of other 10 "Stromnachbarn"
    'DE': 0.3636 # 8/22
    'AT': 0.0455 # 1/22
    'BE': 0.0455
    'CH': 0.0455
    'CZ': 0.0455
    'DK': 0.0909 # 2/22
    'FR': 0.0454
    'GB': 0.0909 # 2/22
    'LU': 0.0454
    'NL': 0.0454
    'NO': 0.0454
    'PL': 0.0454
    'SE': 0.0454

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#co2-budget
co2_budget:
  2020: 0.800 # 20% reduction by 2020
  2025: 0.600
  2030: 0.450 # 55% reduction by 2030 (Ff55)
  2035: 0.250
  2040: 0.100 # goal to be set next year
  2045: 0.050
  2050: 0.000 # climate-neutral by 2050

co2_budget_national:
  2020:
    DE: 0.6
  2030:
    DE: 0.35
  2040:
    DE: 0.12
  2050:
    DE: 0.

limits_min:
  Generator:
    onwind:
      DE:
        2020: 50
        2030: 100
        2040: 160
        2050: 200
    offwind:
      DE:
        2020: 1
        2030: 20
        2040: 25
        2050: 25
    solar:
      DE:
        2020: 50
        2030: 215
        2040: 300
        2050: 400
  Link:
    H2 Electrolysis:
      DE:
        2020: 0
        2030: 10
        2040: 50
        2050: 80

h2_import_max:
  DE:
    2020: 0
    2030: 20
    2040: 100
    2050: 200

new_decentral_fossil_boiler_ban:
  DE: 2029

coal_generation_ban:
  DE: 2038


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  district_heating:
    potential: 0.4
    progress:
      2020: 0.0
      2030: 0.3
      2040: 0.6
      2050: 1.0
  co2_budget_national: true
  #TBD what to include in config
  #relax so no infeasibility in 2050 with no land transport demand
  min_part_load_fischer_tropsch: 0.
  regional_methanol_demand: true  #set to true if regional CO2 constraints needed
  regional_oil_demand: true  #set to true if regional CO2 constraints needed
  biogas_upgrading_cc: true
  cluster_heat_buses: true
  # this needs to be taken from ariadne database
  reduce_space_heat_exogenously_factor:
    2020: 0.0
    2025: 0.05
    2030: 0.10
    2035: 0.16
    2040: 0.22
    2045: 0.25
    2050: 0.35

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#industry
industry:
  St_primary_fraction:
    2020: 0.6
    2025: 0.55
    2030: 0.5
    2035: 0.45
    2040: 0.4
    2045: 0.35
    2050: 0.3

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solving
solving:
  walltime: "12:00:00"
  mem: 140000 #30000 is OK for 22 nodes, 365H; 140000 for 22 nodes 3H; 400000 for 44 nodes 3H
  options:
    load_shedding: false

plotting:
  tech_colors:
    load: "#111100"
