# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  name: "231208-fixprocessemissions-365H"
  scenarios:
    enable: true
  shared_resources: true #stops recalculating
  disable_progressbar: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  simpl:
  - ''
  ll:
  - vopt
  clusters:
  - 22
  opts:
  - ''
  sector_opts:
    - 365H-T-H-B-I-A-solar+p3-linemaxext15
  planning_horizons:
  - 2020
  - 2030
  - 2040
  - 2050

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
# Germany plus 12 "Stromnachbarn"
countries: ['AT', 'BE', 'CH', 'CZ', 'DE', 'DK', 'FR', 'GB', 'LU', 'NL', 'NO', 'PL', 'SE']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: true # set to false once initial data is retrieved
  retrieve_cutout: false # set to false once initial data is retrieved

focus_weights:
# 22 nodes: 8 for Germany, 2 each for Denmark and UK, 1 per each of other 10 "Stromnachbarn"
  'DE': 0.3636 # 8/22
  'AT': 0.0455 # 1/22
  'BE': 0.0455
  'CH': 0.0455
  'CZ': 0.0455
  'DK': 0.0909 # 2/22
  'FR': 0.0454
  'GB': 0.0909 # 2/22
  'LU': 0.0454
  'NL': 0.0454
  'NO': 0.0454
  'PL': 0.0454
  'SE': 0.0454

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#co2-budget
co2_budget:
  2020: 0.800 # 20% reduction by 2020
  2025: 0.600
  2030: 0.450 # 55% reduction by 2030 (Ff55)
  2035: 0.250
  2040: 0.100 # goal to be set next year
  2045: 0.050
  2050: 0.000 # climate-neutral by 2050

co2_budget_national:
  select_unselect_all: true # if true, add national constraints for all countries; if all, add national constraints for none
  exclude_include: [] # if all_countries is true, add countries to exclude; if all_countries is false, add countries to include
  2020:
    'DE': 0.6
    'AT': 0.8
    'BE': 0.8
    'CH': 0.8
    'CZ': 0.8
    'DK': 0.8
    'FR': 0.8
    'GB': 0.8
    'LU': 0.8
    'NL': 0.8
    'NO': 0.8
    'PL': 0.8
    'SE': 0.8
  2030:
    'DE': 0.350
    'AT': 0.450
    'BE': 0.450
    'CH': 0.450
    'CZ': 0.450
    'DK': 0.450
    'FR': 0.450
    'GB': 0.450
    'LU': 0.450
    'NL': 0.450
    'NO': 0.450
    'PL': 0.450
    'SE': 0.450
  2040:
    'DE': 0.120
    'AT': 0.200
    'BE': 0.200
    'CH': 0.200
    'CZ': 0.200
    'DK': 0.200
    'FR': 0.200
    'GB': 0.200
    'LU': 0.200
    'NL': 0.200
    'NO': 0.200
    'PL': 0.200
    'SE': 0.200
  2050:
    'DE': 0.000
    'AT': 0.000
    'BE': 0.000
    'CH': 0.000
    'CZ': 0.000
    'DK': 0.000
    'FR': 0.000
    'GB': 0.000
    'LU': 0.000
    'NL': 0.000
    'NO': 0.000
    'PL': 0.000
    'SE': 0.000

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  district_heating:
    potential: 0.6
    progress:
      2020: 0.0
      2030: 0.3
      2040: 0.6
      2050: 1.0
  co2_budget_national: true
  #TBD what to include in config
  #relax so no infeasibility in 2050 with no land transport demand
  min_part_load_fischer_tropsch: 0.7

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#industry
industry:
  St_primary_fraction:
    2020: 0.6
    2025: 0.55
    2030: 0.5
    2035: 0.45
    2040: 0.4
    2045: 0.35
    2050: 0.3
  #TBD what to include in config

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solving
solving:
  walltime: "12:00:00"
  options:
    load_shedding: false

plotting:
  tech_colors:
    load: "#111100"
