# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

KN2045_Bal_v4:
# Ausgewogener Mix an Technologien zur Dekarbonisierung der Sektoren
# Breites Energieträgerportfolio in der Endenergie (Strom, Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbare Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau
# dient als Referenzszenario in der Familie der Ariadne-Szenarien

  clustering:
    temporal:
      resolution_sector: 365H

  iiasa_database:
    db_name: ariadne_intern
    model_name: Hybrid # should be Leitmodell
    scenario: 8Gt_EnSec # should be consistent with KN2045_Bal_v4
    region: Deutschland

  # boundary condition of maximum volumes
  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 40
        2040: 80
        2045: 125 # scenario guidelines
    # constrain hydrogen import in TWh
    h2_import:
      DE:
        2020: 0
        2025: 5
        2030: 15 # scenario guidelines 
        2035: 115
        2040: 220
        2045: 325 # scenario guidelines
    # import of h2 derivatives in TWh
    h2_derivate_import:
      DE:
        2020: 0
        2025: 0
        2030: 10 # scenario guidelines
        2035: 105
        2040: 200
        2045: 300 # scenario guidelines
    electrolysis:
      DE:
        2020: 0
        2025: 5
        2030: 45 # scenario guidelines
        2035: 130
        2040: 215
        2045: 300 # scenario guidelines
  # boundary condition of minimum volumes
  limits_volume_min:
    electrolysis:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 0
  # sector boundary conditions
  sector:
    # technology mix in transportation from "REMIND Hybrid 8Gt_Bal_v3"
    land_transport_fuel_cell_share:
      2020: 0.004
      2025: 0.036
      2030: 0.067
      2035: 0.048
      2040: 0.025
      2045: 0.009
    land_transport_electric_share:
      2020: 0.005
      2025: 0.061
      2030: 0.243
      2035: 0.520
      2040: 0.740
      2045: 0.874
    land_transport_ice_share:
      2020: 0.991
      2025: 0.903
      2030: 0.690
      2035: 0.432
      2040: 0.235
      2045: 0.118
    # technology mix in navigation
    shipping_hydrogen_share:
      2020: 0.000
      2025: 0.000
      2030: 0.024
      2035: 0.052
      2040: 0.080
      2045: 0.114
    shipping_methanol_share:
      2020: 0.000
      2025: 0.000
      2030: 0.000
      2035: 0.000
      2040: 0.000
      2045: 0.000
    shipping_oil_share:
      2020: 1.000
      2025: 1.000
      2030: 0.976
      2035: 0.948
      2040: 0.920
      2045: 0.886

############################################################################################################

KN2045_Elec_v4:
# Fokus auf dem Hochlauf von Technologien zur direkten Elektrifizierung der Sektoren
# Strom als präferierter Energieträger in der Endenergie, andere Energieträger ergänzend, wo nötig (Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbaren Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau

  clustering:
    temporal:
      resolution_sector: 365H

  iiasa_database:
    db_name: ariadne_intern
    model_name: Hybrid # should be Leitmodell
    scenario: 8Gt_EnSec # should be consistent with KN2045_Elec_v4
    region: Deutschland

  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 50
        2040: 100
        2045: 150 # scenario guidelines
    # constrain hydrogen import in TWh
    h2_import:
      DE:
        2020: 0
        2025: 5
        2030: 10 # scenario guidelines 
        2035: 90
        2040: 170
        2045: 250 # scenario guidelines
    # import of h2 derivatives in TWh
    h2_derivate_import:
      DE:
        2020: 0
        2025: 0
        2030: 10 # scenario guidelines
        2035: 70
        2040: 130
        2045: 200 # scenario guidelines
    electrolysis:
      DE:
        2020: 0
        2025: 5
        2030: 45 # scenario guidelines
        2035: 95
        2040: 145
        2045: 200 # scenario guidelines
  # boundary condition of minimum volumes
  limits_volume_min:
    electrolysis:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 0

  sector:
    # technology mix in transportation from "REMIND Hybrid 8Gt_Bal_v3"
    land_transport_fuel_cell_share:
      2020: 0.004
      2025: 0.036
      2030: 0.067
      2035: 0.048
      2040: 0.025
      2045: 0.009
    land_transport_electric_share:
      2020: 0.005
      2025: 0.061
      2030: 0.243
      2035: 0.520
      2040: 0.740
      2045: 0.874
    land_transport_ice_share:
      2020: 0.991
      2025: 0.903
      2030: 0.690
      2035: 0.432
      2040: 0.235
      2045: 0.118

    shipping_hydrogen_share:
      2020: 0.000
      2025: 0.000
      2030: 0.024
      2035: 0.052
      2040: 0.080
      2045: 0.114
    shipping_methanol_share:
      2020: 0.000
      2025: 0.000
      2030: 0.000
      2035: 0.000
      2040: 0.000
      2045: 0.000
    shipping_oil_share:
      2020: 1.000
      2025: 1.000
      2030: 0.976
      2035: 0.948
      2040: 0.920
      2045: 0.886

############################################################################################################

KN2045_H2_v4:
# Fokus stärker auf dem Hochlauf von Technologien zur indirekten Elektrifizierung der Sektoren
# Verstärkter Einsatz von Wasserstoff und synthetischen Kraftstoffen - erneuerbar erzeugt und auch importiert
# Direkte Elektrifizierung spielt dennoch wesentliche Rolle bei der Dekarbonisierung der Endenergie
# Ausbau der erneuerbaren Stromerzeugung erreicht politisch gesetzte Ziele

  clustering:
    temporal:
      resolution_sector: 365H

  iiasa_database:
    db_name: ariadne_intern
    model_name: Hybrid # should be Leitmodell
    scenario: 8Gt_EnSec # should be consistent with KN2045_Elec_v4
    region: Deutschland

  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 30
        2040: 70
        2045: 100 # scenario guidelines
    # constrain hydrogen import in TWh
    h2_import:
      DE:
        2020: 0
        2025: 5
        2030: 45 # scenario guidelines 
        2035: 155
        2040: 265
        2045: 400 # scenario guidelines
    # import of h2 derivatives in TWh
    h2_derivate_import:
      DE:
        2020: 0
        2025: 0
        2030: 10 # scenario guidelines
        2035: 140
        2040: 270
        2045: 400 # scenario guidelines
    electrolysis:
      DE:
        2025: 5
        2030: 45 # scenario guidelines
        2035: 160
        2040: 275
        2045: 400 # scenario guidelines

  limits_volume_min:
    electrolysis:
      DE:
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 200

  sector:
    # technology mix in transportation from "REMIND Hybrid 8Gt_Bal_v3"
    land_transport_fuel_cell_share:
      2020: 0.004
      2025: 0.036
      2030: 0.067
      2035: 0.048
      2040: 0.025
      2045: 0.009
    land_transport_electric_share:
      2020: 0.005
      2025: 0.061
      2030: 0.243
      2035: 0.520
      2040: 0.740
      2045: 0.874
    land_transport_ice_share:
      2020: 0.991
      2025: 0.903
      2030: 0.690
      2035: 0.432
      2040: 0.235
      2045: 0.118
    # technology mix in navigation
    shipping_hydrogen_share:
      2020: 0.000
      2025: 0.000
      2030: 0.024
      2035: 0.052
      2040: 0.080
      2045: 0.114
    shipping_methanol_share:
      2020: 0.000
      2025: 0.000
      2030: 0.000
      2035: 0.000
      2040: 0.000
      2045: 0.000
    shipping_oil_share:
      2020: 1.000
      2025: 1.000
      2030: 0.976
      2035: 0.948
      2040: 0.920
      2045: 0.886

# KN2045plus_EasyRide:

# KN2045plus_LowDemand:

# KN2045minus_WorstCase:

# KN2045minus_SupplyFocus:
