# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

CurrentPolicies:
# Trend Szenario
# Suggestion (Tom): "policy from 2030 is frozen"
# conservative development after 2030
# fixing CO2 budget at 2030 value for 2035-2050
# reducing VRE targets in 2030 to 75% of the target (following REMIND)
# not forcing H2 production
# orient transport transformation towards ALADIN (Fraunhofer model) results
# industry transformation towards FORECAST results
# consider not assuming Kernnetz

  clustering:
    temporal:
      resolution_sector: 365H

  # Kernnetz is not assumed to be built
  wasserstoff_kernnetz:
    enable: false

  iiasa_database:
    # TODO: wait for REMod v1.0 to upload a Trend scenario
    reference_scenario: Trend

  co2_budget:
    2020: 0.800 # 20% reduction by 2020
    2025: 0.600
    2030: 0.450 # 55% reduction by 2030 (Ff55)
    2035: 0.450 # stagnation for the Trend scenario
    2040: 0.450
    2045: 0.450
    2050: 0.450

  co2_budget_national:
    2020:
      DE: 0.728
    2025:
      DE: 0.571
    2030:
      DE: 0.396
    2035:
      DE: 0.396 # 2030 value
    2040:
      DE: 0.396 # 2030 value
    2045:
      DE: 0.396 # 2030 value
    2050:
      DE: 0.396 # 2030 value

  limits_capacity_min:
      Generator:
        onwind:
          DE:
            2020: 48
            2025: 61
            2030: 86.5 # 75 % Wind-an-Land Law
            2035: 117.75 # 75 % Wind-an-Land Law
            2040: 120 # 75 % Wind-an-Land Law
            2045: 120
        offwind:
          DE:
            2020: 7.77
            2025: 8
            2030: 22.5 # 75 % Wind-auf-See Law
            2035: 30 # 75 % Wind-auf-See Law assuming at least 1/3 of difference reached in 2040
            2040: 32.5 # 75 % Wind-auf-See Law
            2045: 52.5 # 75 % Wind-auf-See Law
        solar:
          DE:
            2020: 59
            # EEG2023; Ziel for 2024: 88 GW and for 2026: 128 GW, 
            # assuming at least 1/3 of difference reached in 2025
            2025: 101 
            2030: 161.25 # 75 % PV strategy
            2035: 231.75
            2040: 300 # 75 % PV strategy
            2045: 300

  # boundary condition of maximum volumes
  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 40
        2040: 80
        2045: 125
    electrolysis:
    # boundary condition lower?
      DE:
        2020: 0
        2025: 5
        2030: 45
        2035: 130
        2040: 215
        2045: 300
    h2_derivate_import:
    # boundary condition lower?
      DE:
        2020: 0
        2025: 0
        2030: 10
        2035: 105
        2040: 200
        2045: 300
    h2_import:
    # boundary condition lower?
      DE:
        2020: 0
        2025: 5
        2030: 15
        2035: 115
        2040: 220
        2045: 325
  limits_volume_min:
    electrolysis:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 0
  # sector boundary conditions
  sector:
  # read that in from REMod - Fraunhofer
    land_transport_electric_share:
      2020: 0.0047
      2025: 0.0611
      2030: 0.243
      2035: 0.5199
      2040: 0.74
      2045: 0.8737
    land_transport_fuel_cell_share:
      2020: 0.004
      2025: 0.0362
      2030: 0.0667
      2035: 0.0485
      2040: 0.0252
      2045: 0.0085
    land_transport_ice_share:
      2020: 0.9913
      2025: 0.9027
      2030: 0.6903
      2035: 0.4316
      2040: 0.2348
      2045: 0.1178
    shipping_hydrogen_share:
      2020: 0.0
      2025: 0.0
      2030: 0.0238
      2035: 0.0522
      2040: 0.0802
      2045: 0.1142
    shipping_methanol_share:
      2020: 0.0
      2025: 0.0
      2030: 0.0
      2035: 0.0
      2040: -0.0
      2045: 0.0
    shipping_oil_share:
      2020: 1.0
      2025: 1.0
      2030: 0.9762
      2035: 0.9478
      2040: 0.9198
      2045: 0.8858

KN2045_Bal_v4:
# Ausgewogener Mix an Technologien zur Dekarbonisierung der Sektoren
# Breites Energieträgerportfolio in der Endenergie (Strom, Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbare Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau
# dient als Referenzszenario in der Familie der Ariadne-Szenarien

  clustering:
    temporal:
      resolution_sector: 365H

  iiasa_database:
    reference_scenario: 8Gt_Bal_v3

  co2_budget_national:
    2020:
      DE: 0.728
    2025:
      DE: 0.571
    2030:
      DE: 0.396
    2035:
      DE: 0.258
    2040:
      DE: 0.118
    2045:
      DE: -0.028
    2050:
      DE: -0.024

  # boundary condition of maximum volumes
  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 40
        2040: 80
        2045: 125
    electrolysis:
      DE:
        2020: 0
        2025: 5
        2030: 45
        2035: 130
        2040: 215
        2045: 300
    h2_derivate_import:
      DE:
        2020: 0
        2025: 0
        2030: 10
        2035: 105
        2040: 200
        2045: 300
    h2_import:
      DE:
        2020: 0
        2025: 5
        2030: 15
        2035: 115
        2040: 220
        2045: 325
  limits_volume_min:
    electrolysis:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 0
  # sector boundary conditions
  sector:
    land_transport_electric_share:
      2020: 0.0047
      2025: 0.0611
      2030: 0.243
      2035: 0.5199
      2040: 0.74
      2045: 0.8737
    land_transport_fuel_cell_share:
      2020: 0.004
      2025: 0.0362
      2030: 0.0667
      2035: 0.0485
      2040: 0.0252
      2045: 0.0085
    land_transport_ice_share:
      2020: 0.9913
      2025: 0.9027
      2030: 0.6903
      2035: 0.4316
      2040: 0.2348
      2045: 0.1178
    shipping_hydrogen_share:
      2020: 0.0
      2025: 0.0
      2030: 0.0238
      2035: 0.0522
      2040: 0.0802
      2045: 0.1142
    shipping_methanol_share:
      2020: 0.0
      2025: 0.0
      2030: 0.0
      2035: 0.0
      2040: -0.0
      2045: 0.0
    shipping_oil_share:
      2020: 1.0
      2025: 1.0
      2030: 0.9762
      2035: 0.9478
      2040: 0.9198
      2045: 0.8858

KN2045_Elec_v4:
# Fokus auf dem Hochlauf von Technologien zur direkten Elektrifizierung der Sektoren
# Strom als präferierter Energieträger in der Endenergie, andere Energieträger ergänzend, wo nötig (Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbaren Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau

  clustering:
    temporal:
      resolution_sector: 365H

  iiasa_database:
    reference_scenario: 8Gt_Elec_v3

  co2_budget_national:
    2020:
      DE: 0.728
    2025:
      DE: 0.571
    2030:
      DE: 0.396
    2035:
      DE: 0.258
    2040:
      DE: 0.118
    2045:
      DE: -0.028
    2050:
      DE: -0.024

  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 50
        2040: 100
        2045: 150
    electrolysis:
      DE:
        2020: 0
        2025: 5
        2030: 45
        2035: 95
        2040: 145
        2045: 200
    h2_derivate_import:
      DE:
        2020: 0
        2025: 0
        2030: 10
        2035: 70
        2040: 130
        2045: 200
    h2_import:
      DE:
        2020: 0
        2025: 5
        2030: 10
        2035: 90
        2040: 170
        2045: 250
  limits_volume_min:
    electrolysis:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 0

  sector:
    land_transport_electric_share:
      2020: 0.0047
      2025: 0.0611
      2030: 0.243
      2035: 0.5199
      2040: 0.74
      2045: 0.8737
    land_transport_fuel_cell_share:
      2020: 0.004
      2025: 0.0362
      2030: 0.0667
      2035: 0.0485
      2040: 0.0252
      2045: 0.0085
    land_transport_ice_share:
      2020: 0.9913
      2025: 0.9027
      2030: 0.6903
      2035: 0.4316
      2040: 0.2348
      2045: 0.1178
    shipping_hydrogen_share:
      2020: 0.0
      2025: 0.0
      2030: 0.0238
      2035: 0.0522
      2040: 0.0802
      2045: 0.1142
    shipping_methanol_share:
      2020: 0.0
      2025: 0.0
      2030: 0.0
      2035: 0.0
      2040: -0.0
      2045: 0.0
    shipping_oil_share:
      2020: 1.0
      2025: 1.0
      2030: 0.9762
      2035: 0.9478
      2040: 0.9198
      2045: 0.8858

KN2045_H2_v4:
# Fokus stärker auf dem Hochlauf von Technologien zur indirekten Elektrifizierung der Sektoren
# Verstärkter Einsatz von Wasserstoff und synthetischen Kraftstoffen - erneuerbar erzeugt und auch importiert
# Direkte Elektrifizierung spielt dennoch wesentliche Rolle bei der Dekarbonisierung der Endenergie
# Ausbau der erneuerbaren Stromerzeugung erreicht politisch gesetzte Ziele

  clustering:
    temporal:
      resolution_sector: 365H

  iiasa_database:
    reference_scenario: 8Gt_H2_v3

  co2_budget_national:
    2020:
      DE: 0.728
    2025:
      DE: 0.573
    2030:
      DE: 0.401
    2035:
      DE: 0.265
    2040:
      DE: 0.135
    2045:
      DE: -0.011
    2050:
      DE: -0.017

  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 30
        2040: 70
        2045: 100 # scenario guidelines
    # constrain hydrogen import in TWh
    h2_import:
      DE:
        2020: 0
        2025: 5
        2030: 45 # scenario guidelines 
        2035: 155
        2040: 265
        2045: 400 # scenario guidelines
    # import of h2 derivatives in TWh
    h2_derivate_import:
      DE:
        2020: 0
        2025: 0
        2030: 10 # scenario guidelines
        2035: 140
        2040: 270
        2045: 400 # scenario guidelines
    electrolysis:
      DE:
        2020: 0
        2025: 5
        2030: 45 # scenario guidelines
        2035: 160
        2040: 275
        2045: 400 # scenario guidelines

  limits_volume_min:
    electrolysis:
      DE:
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 200

  sector:
    land_transport_electric_share:
      2020: 0.0047
      2025: 0.0611
      2030: 0.243
      2035: 0.5199
      2040: 0.74
      2045: 0.8737
    land_transport_fuel_cell_share:
      2020: 0.004
      2025: 0.0362
      2030: 0.0667
      2035: 0.0485
      2040: 0.0252
      2045: 0.0085
    land_transport_ice_share:
      2020: 0.9913
      2025: 0.9027
      2030: 0.6903
      2035: 0.4316
      2040: 0.2348
      2045: 0.1178
    shipping_hydrogen_share:
      2020: 0.0
      2025: 0.0
      2030: 0.0238
      2035: 0.0522
      2040: 0.0802
      2045: 0.1142
    shipping_methanol_share:
      2020: 0.0
      2025: 0.0
      2030: 0.0
      2035: 0.0
      2040: -0.0
      2045: 0.0
    shipping_oil_share:
      2020: 1.0
      2025: 1.0
      2030: 0.9762
      2035: 0.9478
      2040: 0.9198
      2045: 0.8858
